modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/SokyranTheDragon/Sokys_Various_Thing_Pack/issues"
license = "GPL-3.0-or-later"

[[mods]]
modId = "sokys_various_things_pack"
version = "${version}"
displayName = "Soky's Various Things Pack"
authors = "Soky"
description = '''
A mod adding a handful of (mostly) decorative blocks to the game.
'''
logoFile = "assets/sokys_various_things_pack/icon.png"
updateJSONURL = "https://raw.githubusercontent.com/SokyranTheDragon/librush/refs/heads/update_checker/neoforge_update.json"
displayURL = "https://github.com/SokyranTheDragon/Sokys_Various_Thing_Pack"

[[dependencies.sokys_various_things_pack]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sokys_various_things_pack]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sokys_various_things_pack]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sokys_various_things_pack]]
modId = "fusion"
type = "optional"
ordering = "NONE"
reason = "connected textures support"
side = "CLIENT"

[[mixins]]
config = "sokys_various_things_pack.mixins.json"